name: Travel_APP Main

on:
  push:
    branches: [main]

jobs:
  extract-code:
    runs-on: smallappsmain
    defaults:
      run:
        working-directory: /var/www/timbu/staging/travel.app

    steps:
      - uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8

      - name: Remove old actions remote url
        continue-on-error: true
        run: |
          git stash
          git remote rm action

      - name: Pull from github
        id: pull
        run: |
          remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git remote add action $remote_repo
          git pull action main

      - name: change the type of output to standalone
        run: |
          sed -i '/output:/d' next.config.mjs
          sed -i '/const nextConfig = {/a output: \"standalone\"\,' next.config.mjs
      - name: remove old directories
        run: |
          [ -d build.old ] && rm -rf build.old
          [ -d build ] && rm -rf build
      - name: install dependencies
        run: |
          pnpm install --no-frozen-lockfile
          pnpm run build

      - name: copy to the deployment folder
        run: |
          # [ -d build.old ] && rm -rf build.old
          [ -d build ]&& mv build build.old
          mkdir -p .next/media/_next/static
          cp -rf .next/static/* .next/media/_next/static
          cp -rf public/* .next/media
          cp -rf .next build

      - name: restart server
        run: |
          sudo systemctl restart travelstagingapp
